# add the following to _config.yml file
title: Ashita Chandnani
logo: /assets/img/headshot.png
description: MS CS - AI & ML

#show_downloads: true
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
sass:
  style: :compressed
